# Generated by Django 5.2.14 on 2026-06-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsdIdrHistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("close", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "USD/IDR historical data",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UsdIdrPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("yhat", models.FloatField()),
                ("yhat_lower", models.FloatField()),
                ("yhat_upper", models.FloatField()),
                ("model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("date", "model_version")},
            },
        ),
    ]
