# Generated by Django 6.0.5 on 2026-05-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('close', models.FloatField(verbose_name='Closing Price')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV Upload')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historical Data',
                'verbose_name_plural': 'Historical Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UploadedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Uploaded CSV',
                'verbose_name_plural': 'Uploaded CSV',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
